In [1]:
import numpy as np

In [14]:
my_list1=[3,6,2,7,5]
my_list2=[2,6,2,9,5]
my_list3=[9,5,2,12,5]
arr=np.array([my_list1,my_list2,my_list3])

In [15]:
type(arr)

numpy.ndarray

In [62]:
arr[1:,1:3]

array([[6, 2],
       [5, 2]])

In [51]:
arr[1:3,1:3]

array([[6, 2],
       [5, 2]])

In [70]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [73]:
np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [18]:
arr[2,3]

12

In [5]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[3, 6, 2],
       [7, 5, 2],
       [6, 2, 9],
       [5, 9, 5],
       [2, 7, 5]])

In [12]:
arr.reshape(1,15)

array([[3, 6, 2, 7, 5, 2, 6, 2, 9, 5, 9, 5, 2, 7, 5]])

In [13]:
arr.shape

(3, 5)